import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Business from './business'
import Configuration from './configuration'
import Navbar from './navbar'
import { useEffect, useState } from 'react'
import NoteService from '../services/note.service'

const Home: NextPage = () => {
  const [notes, setNotes] = useState([])

  useEffect(() => {
    NoteService.get().then(({ props }) => {
      setNotes(props.notes);
    }
    );
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Harmony explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <div className="grid grid-cols-4 ">
          <div className="col-span-1">
            <Configuration></Configuration>
          </div>

          <div className="col-span-3 h-auto overflow-scroll">
            <Business notes={notes}></Business></div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            Subrosa
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home



